version: '2'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      internal:
        ipv4_address: 172.16.239.2

  postgres:
    image: postgres:alpine
    command: postgres -N 500 -B 4096MB
    environment:
      POSTGRES_PASSWORD: REPLACE_ME
    ports:
      - 5432:5432
    networks:
      internal:
        ipv4_address: 172.16.239.3

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24
          gateway: 172.16.239.1